Visual Studio Code (1.83.1, undefined, desktop)
Jupyter Extension Version: 2023.10.1003070148.
Python Extension Version: 2023.20.0.
Platform: linux (x64).
Workspace folder ~/Code/Python/DAT565_labs/lab1, Home = /home/sam
13:58:12.621 [info] Start refreshing Kernel Picker (1698929892621)
13:58:12.626 [info] Using Pylance
13:58:13.302 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd022c20fb3e009b90b1487f44493d46a7a0c3364d8e13c25e1ba7810ca21a44a3b.~/.pyenv/versions/3.11.6/python.~/.pyenv/versions/3.11.6/python.-m#ipykernel_launcher  (Python Path: ~/.pyenv/versions/3.11.6/bin/python, Pyenv, 3.11.6) for '~/Code/Python/DAT565_labs/lab1/main.ipynb' (disableUI=true)
13:58:13.896 [info] Process Execution: ~/.pyenv/versions/3.11.6/bin/python -m pip list
13:58:13.921 [info] Process Execution: ~/.pyenv/versions/3.11.6/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
13:58:13.932 [info] Process Execution: ~/.pyenv/versions/3.11.6/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"cc94c9f0-c3d3-4835-aa69-abc0f4e95b12" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-6229OFY5fKQMhUTQ.json
    > cwd: ~/Code/Python/DAT565_labs/lab1
13:58:14.003 [info] End refreshing Kernel Picker (1698929892621)
13:58:14.184 [info] ipykernel version & path 6.26.0, ~/.pyenv/versions/3.11.6/lib/python3.11/site-packages/ipykernel/__init__.py for ~/.pyenv/versions/3.11.6/bin/python
13:58:14.518 [warn] StdErr from Kernel Process 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
13:59:42.102 [info] Disposing HostJupyterExecution
13:59:42.102 [info] Dispose Kernel '~/Code/Python/DAT565_labs/lab1/main.ipynb' associated with '~/Code/Python/DAT565_labs/lab1/main.ipynb'
13:59:42.103 [info] Dispose Kernel process 6359.
13:59:42.117 [info] Disposing HostJupyterExecution
13:59:42.152 [warn] Failed to delete connection file file://~/.local/share/jupyter/runtime/kernel-v2-6229OFY5fKQMhUTQ.json for pid 6359 [Canceled (FileSystemError): Canceled
	at E.e (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:27845)
	at Object.stat (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:24555)
	at async pp.delete (~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1003070148-linux-x64/out/extension.node.js:17:19303)
	at async ~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1003070148-linux-x64/out/extension.node.js:24:88505] {
  code: 'Unknown'
}
