Visual Studio Code (1.83.1, undefined, desktop)
Jupyter Extension Version: 2023.10.1003070148.
Python Extension Version: 2023.20.0.
Platform: linux (x64).
Workspace folder ~/Code/Python/DAT565_labs/lab1, Home = /home/sam
13:55:23.553 [info] Start refreshing Kernel Picker (1698929723553)
13:55:23.558 [info] Using Pylance
13:55:23.601 [info] Start refreshing Interpreter Kernel Picker
13:55:25.038 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd022c20fb3e009b90b1487f44493d46a7a0c3364d8e13c25e1ba7810ca21a44a3b.~/.pyenv/versions/3.11.6/python.~/.pyenv/versions/3.11.6/python.-m#ipykernel_launcher  (Python Path: ~/.pyenv/versions/3.11.6/bin/python, Pyenv, 3.11.6) for '~/Code/Python/DAT565_labs/lab1/main.ipynb' (disableUI=true)
13:55:25.293 [info] Process Execution: ~/.pyenv/versions/3.11.6/bin/python -m pip list
13:55:25.310 [info] Process Execution: ~/.pyenv/versions/3.11.6/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
13:55:25.324 [info] Process Execution: ~/.pyenv/versions/3.11.6/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"7446238a-cbc1-4df0-9e46-64f9aec357dc" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-4754fV1QtxWhhxDn.json
    > cwd: ~/Code/Python/DAT565_labs/lab1
13:55:25.639 [info] ipykernel version & path 6.26.0, ~/.pyenv/versions/3.11.6/lib/python3.11/site-packages/ipykernel/__init__.py for ~/.pyenv/versions/3.11.6/bin/python
13:55:26.075 [warn] StdErr from Kernel Process 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
13:55:26.330 [info] Process Execution: ~/.pyenv/versions/3.11.6/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1003070148-linux-x64/pythonFiles/printJupyterDataDir.py
13:55:26.885 [info] End refreshing Kernel Picker (1698929723553)
13:55:38.488 [info] Disposing HostJupyterExecution
13:55:38.488 [info] Dispose Kernel '~/Code/Python/DAT565_labs/lab1/main.ipynb' associated with '~/Code/Python/DAT565_labs/lab1/main.ipynb'
13:55:38.489 [info] Dispose Kernel process 4923.
13:55:38.505 [info] Disposing HostJupyterExecution
13:55:38.552 [warn] Failed to delete connection file file://~/.local/share/jupyter/runtime/kernel-v2-4754fV1QtxWhhxDn.json for pid 4923 [Canceled (FileSystemError): Canceled
	at E.e (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:27845)
	at Object.stat (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:24555)
	at async pp.delete (~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1003070148-linux-x64/out/extension.node.js:17:19303)
	at async ~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1003070148-linux-x64/out/extension.node.js:24:88505] {
  code: 'Unknown'
}
